spring.application.name=pacientes

server.port=8082

auth.url=http://174.129.112.201:8081/auth/validate

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://bd.ce2dl2fmudwp.us-east-1.rds.amazonaws.com:3306/cuidado_seguro_pacientes?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:cuidadoseguro}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

resilience4j.circuitbreaker.instances.authService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.authService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.authService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.authService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.authService.permittedNumberOfCallsInHalfOpenState=3

spring.output.ansi.enabled=always
